"""update dog friendly places table

Revision ID: 32f1bf8ecb99
Revises: f9cd5961f532
Create Date: 2026-03-23 23:55:37.053026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32f1bf8ecb99'
down_revision: Union[str, Sequence[str], None] = 'f9cd5961f532'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dog_friendly_places', sa.Column('dogfriendly_place_city', sa.String(length=50), nullable=False))
    op.add_column('dog_friendly_places', sa.Column('dogfriendly_place_street', sa.String(length=127), nullable=False))
    op.add_column('dog_friendly_places', sa.Column('dogfriendly_place_building_number', sa.String(length=20), nullable=False))
    op.add_column('dog_friendly_places', sa.Column('dogfriendly_place_lat', sa.Numeric(), nullable=False))
    op.add_column('dog_friendly_places', sa.Column('dogfriendly_place_lon', sa.Numeric(), nullable=False))
    op.add_column('dog_friendly_places', sa.Column('dogfriendly_place_geocoder_precision', sa.String(length=50), nullable=False))
    op.add_column('dog_friendly_places', sa.Column('dogfriendly_place_working_hours', sa.String(length=255), nullable=False))
    op.add_column('dog_friendly_places', sa.Column('dogfriendly_place_is_24_7', sa.Boolean(), nullable=False))
    op.add_column('dog_friendly_places', sa.Column('dogfriendly_place_status', sa.String(length=20), nullable=False))
    op.add_column('dog_friendly_places', sa.Column('dogfriendly_place_last_verified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('dog_friendly_places', 'dogfriendly_place_rating')
    op.drop_column('dog_friendly_places', 'dogfriendly_place_address')
    op.drop_column('dog_friendly_places', 'dogfriendly_place_photo')
    op.drop_column('dog_friendly_places', 'dogfriendly_place_work_hours')
    op.drop_column('dog_friendly_places', 'dogfriendly_place_description')
    op.drop_column('dog_friendly_places', 'dogfriendly_place_contacts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dog_friendly_places', sa.Column('dogfriendly_place_contacts', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('dog_friendly_places', sa.Column('dogfriendly_place_description', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('dog_friendly_places', sa.Column('dogfriendly_place_work_hours', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('dog_friendly_places', sa.Column('dogfriendly_place_photo', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('dog_friendly_places', sa.Column('dogfriendly_place_address', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('dog_friendly_places', sa.Column('dogfriendly_place_rating', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.drop_column('dog_friendly_places', 'dogfriendly_place_last_verified')
    op.drop_column('dog_friendly_places', 'dogfriendly_place_status')
    op.drop_column('dog_friendly_places', 'dogfriendly_place_is_24_7')
    op.drop_column('dog_friendly_places', 'dogfriendly_place_working_hours')
    op.drop_column('dog_friendly_places', 'dogfriendly_place_geocoder_precision')
    op.drop_column('dog_friendly_places', 'dogfriendly_place_lon')
    op.drop_column('dog_friendly_places', 'dogfriendly_place_lat')
    op.drop_column('dog_friendly_places', 'dogfriendly_place_building_number')
    op.drop_column('dog_friendly_places', 'dogfriendly_place_street')
    op.drop_column('dog_friendly_places', 'dogfriendly_place_city')
    # ### end Alembic commands ###
