"""add auth provider table

Revision ID: 34c612ec2c36
Revises: 3a7d1e5c9b2f
Create Date: 2026-04-19 21:04:43.126980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34c612ec2c36'
down_revision: Union[str, Sequence[str], None] = '3a7d1e5c9b2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_identities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('user_email', sa.String(length=50), nullable=True),
    sa.Column('user_password_hash', sa.Text(), nullable=False),
    sa.Column('user_telegram_id', sa.BIGINT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users_info.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_identities_user_email'), 'auth_identities', ['user_email'], unique=True)
    op.create_index(op.f('ix_auth_identities_user_telegram_id'), 'auth_identities', ['user_telegram_id'], unique=True)
    op.drop_constraint(op.f('fk_animals_breeds_animal_type_id'), 'animals_breeds', type_='foreignkey')
    op.create_foreign_key(None, 'animals_breeds', 'animals_types', ['animal_type_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('pets_info_animal_type_id_fkey'), 'pets_info', type_='foreignkey')
    op.create_foreign_key(None, 'pets_info', 'animals_types', ['animal_type_id'], ['id'], ondelete='CASCADE')
    op.drop_column('users_info', 'auth_provider')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_info', sa.Column('auth_provider', sa.VARCHAR(length=20), server_default=sa.text("'email'::character varying"), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'pets_info', type_='foreignkey')
    op.create_foreign_key(op.f('pets_info_animal_type_id_fkey'), 'pets_info', 'animals_types', ['animal_type_id'], ['id'], ondelete='CASCADE', initially='DEFERRED', deferrable=True)
    op.drop_constraint(None, 'animals_breeds', type_='foreignkey')
    op.create_foreign_key(op.f('fk_animals_breeds_animal_type_id'), 'animals_breeds', 'animals_types', ['animal_type_id'], ['id'], ondelete='CASCADE', initially='DEFERRED', deferrable=True)
    op.drop_index(op.f('ix_auth_identities_user_telegram_id'), table_name='auth_identities')
    op.drop_index(op.f('ix_auth_identities_user_email'), table_name='auth_identities')
    op.drop_table('auth_identities')
    # ### end Alembic commands ###
