"""add to llm chats and messages

Revision ID: 3ae998d30070
Revises: 9ded3226e584
Create Date: 2026-04-25 18:54:54.745641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ae998d30070'
down_revision: Union[str, Sequence[str], None] = '9ded3226e584'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_chats_messages', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('llm_chats_messages', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_chats_messages', 'error_message')
    op.drop_column('llm_chats_messages', 'status')
    # ### end Alembic commands ###
