"""update llmchat

Revision ID: 3de7b33dbfe2
Revises: 921c0605b450
Create Date: 2026-05-04 09:16:50.257867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3de7b33dbfe2'
down_revision: Union[str, Sequence[str], None] = '921c0605b450'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_chats', sa.Column('pet_id', sa.Integer(), nullable=False))
    op.alter_column('llm_chats', 'chat_title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_foreign_key(None, 'llm_chats', 'pets_info', ['pet_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'llm_chats', type_='foreignkey')
    op.alter_column('llm_chats', 'chat_title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('llm_chats', 'pet_id')
    # ### end Alembic commands ###
