"""update dog friendly and vets

Revision ID: 4773b39cfdbb
Revises: 32f1bf8ecb99
Create Date: 2026-03-24 00:03:23.537403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4773b39cfdbb'
down_revision: Union[str, Sequence[str], None] = '32f1bf8ecb99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_dog_friendly_place', 'dog_friendly_places', ['dogfriendly_place_name', 'dogfriendly_place_city', 'dogfriendly_place_street', 'dogfriendly_place_building_number'])
    op.create_unique_constraint('unique_vet_clinic', 'vet_clinics', ['vet_name', 'vet_city', 'vet_street', 'vet_building_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_vet_clinic', 'vet_clinics', type_='unique')
    op.drop_constraint('unique_dog_friendly_place', 'dog_friendly_places', type_='unique')
    # ### end Alembic commands ###
