"""update llm tables

Revision ID: 55e00d599145
Revises: 4773b39cfdbb
Create Date: 2026-03-24 18:23:32.275696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '55e00d599145'
down_revision: Union[str, Sequence[str], None] = '4773b39cfdbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chat_title', sa.String(length=255), nullable=False),
    sa.Column('chat_custom_instructions', sa.Text(), nullable=True),
    sa.Column('chat_created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users_info.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('llm_chats_messages', sa.Column('chat_id', sa.Integer(), nullable=False))
    op.add_column('llm_chats_messages', sa.Column('content', sa.Text(), nullable=False))
    op.add_column('llm_chats_messages', sa.Column('message_created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('ix_llm_chats_messages_conversation_id'), table_name='llm_chats_messages')
    op.drop_index(op.f('ix_llm_chats_messages_message_hash'), table_name='llm_chats_messages')
    op.create_index(op.f('ix_llm_chats_messages_chat_id'), 'llm_chats_messages', ['chat_id'], unique=False)
    op.create_foreign_key(None, 'llm_chats_messages', 'llm_chats_messages', ['chat_id'], ['id'], ondelete='CASCADE')
    op.drop_column('llm_chats_messages', 'message_hash')
    op.drop_column('llm_chats_messages', 'conversation_id')
    op.drop_column('llm_chats_messages', 'message_text')
    op.drop_column('llm_chats_messages', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_chats_messages', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('llm_chats_messages', sa.Column('message_text', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('llm_chats_messages', sa.Column('conversation_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.add_column('llm_chats_messages', sa.Column('message_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'llm_chats_messages', type_='foreignkey')
    op.drop_index(op.f('ix_llm_chats_messages_chat_id'), table_name='llm_chats_messages')
    op.create_index(op.f('ix_llm_chats_messages_message_hash'), 'llm_chats_messages', ['message_hash'], unique=True)
    op.create_index(op.f('ix_llm_chats_messages_conversation_id'), 'llm_chats_messages', ['conversation_id'], unique=False)
    op.drop_column('llm_chats_messages', 'message_created_at')
    op.drop_column('llm_chats_messages', 'content')
    op.drop_column('llm_chats_messages', 'chat_id')
    op.drop_table('llm_chats')
    # ### end Alembic commands ###
