"""reshape llm chat tables

Revision ID: 55e00d599145
Revises: 4773b39cfdbb
Create Date: 2026-03-24 18:23:32.275696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '55e00d599145'
down_revision: Union[str, Sequence[str], None] = '4773b39cfdbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS llm_chats (
            id SERIAL PRIMARY KEY,
            user_id INTEGER NOT NULL REFERENCES users_info(id) ON DELETE CASCADE,
            chat_title VARCHAR(255) NOT NULL,
            chat_custom_instructions TEXT,
            chat_created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )

    op.execute(
        """
        ALTER TABLE llm_chats_messages
        ADD COLUMN IF NOT EXISTS chat_id INTEGER
        """
    )
    op.execute(
        """
        ALTER TABLE llm_chats_messages
        ADD COLUMN IF NOT EXISTS content TEXT
        """
    )
    op.execute(
        """
        ALTER TABLE llm_chats_messages
        ADD COLUMN IF NOT EXISTS message_created_at TIMESTAMPTZ DEFAULT now()
        """
    )

    op.execute(
        """
        INSERT INTO llm_chats (user_id, chat_title)
        SELECT DISTINCT user_id, 'Imported Chat'
        FROM llm_chats_messages msg
        WHERE NOT EXISTS (
            SELECT 1
            FROM llm_chats chat
            WHERE chat.user_id = msg.user_id
        )
        """
    )
    op.execute(
        """
        UPDATE llm_chats_messages msg
        SET chat_id = chat.id
        FROM llm_chats chat
        WHERE chat.user_id = msg.user_id
          AND msg.chat_id IS NULL
        """
    )
    op.execute(
        """
        UPDATE llm_chats_messages
        SET content = message_text
        WHERE content IS NULL
        """
    )
    op.execute(
        """
        UPDATE llm_chats_messages
        SET message_created_at = created_at
        WHERE message_created_at IS NULL
        """
    )
    op.execute(
        """
        ALTER TABLE llm_chats_messages
        ALTER COLUMN chat_id SET NOT NULL
        """
    )
    op.execute(
        """
        ALTER TABLE llm_chats_messages
        ALTER COLUMN content SET NOT NULL
        """
    )
    op.execute(
        """
        ALTER TABLE llm_chats_messages
        ALTER COLUMN message_created_at SET NOT NULL
        """
    )
    op.execute("DROP INDEX IF EXISTS ix_llm_chats_messages_conversation_id")
    op.execute("DROP INDEX IF EXISTS ix_llm_chats_messages_message_hash")
    op.execute(
        """
        CREATE INDEX IF NOT EXISTS ix_llm_chats_messages_chat_id
        ON llm_chats_messages (chat_id)
        """
    )
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1
                FROM pg_constraint
                WHERE conrelid = 'llm_chats_messages'::regclass
                  AND conname = 'fk_llm_chats_messages_chat_id_llm_chats'
            ) THEN
                ALTER TABLE llm_chats_messages
                ADD CONSTRAINT fk_llm_chats_messages_chat_id_llm_chats
                FOREIGN KEY (chat_id)
                REFERENCES llm_chats(id)
                ON DELETE CASCADE;
            END IF;
        END
        $$;
        """
    )
    op.execute("ALTER TABLE llm_chats_messages DROP COLUMN IF EXISTS message_hash")
    op.execute("ALTER TABLE llm_chats_messages DROP COLUMN IF EXISTS conversation_id")
    op.execute("ALTER TABLE llm_chats_messages DROP COLUMN IF EXISTS message_text")
    op.execute("ALTER TABLE llm_chats_messages DROP COLUMN IF EXISTS created_at")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_chats_messages', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('llm_chats_messages', sa.Column('message_text', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('llm_chats_messages', sa.Column('conversation_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.add_column('llm_chats_messages', sa.Column('message_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'llm_chats_messages', type_='foreignkey')
    op.drop_index(op.f('ix_llm_chats_messages_chat_id'), table_name='llm_chats_messages')
    op.create_index(op.f('ix_llm_chats_messages_message_hash'), 'llm_chats_messages', ['message_hash'], unique=True)
    op.create_index(op.f('ix_llm_chats_messages_conversation_id'), 'llm_chats_messages', ['conversation_id'], unique=False)
    op.drop_column('llm_chats_messages', 'message_created_at')
    op.drop_column('llm_chats_messages', 'content')
    op.drop_column('llm_chats_messages', 'chat_id')
    op.drop_table('llm_chats')
    # ### end Alembic commands ###
