"""initial schema

Revision ID: 57adcc7b665c
Revises: 
Create Date: 2026-03-12 01:35:52.312536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57adcc7b665c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animals_breeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_breed_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('animal_breed_name')
    )
    op.create_table('animals_pedigrees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_pedigree', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('animal_pedigree')
    )
    op.create_table('animals_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('animal_name')
    )
    op.create_table('custom_documents_names',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('documents_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_name')
    )
    op.create_table('dog_friendly_places',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dogfriendly_place_name', sa.String(length=50), nullable=False),
    sa.Column('dogfriendly_place_address', sa.String(length=50), nullable=False),
    sa.Column('dogfriendly_place_rating', sa.Numeric(), nullable=False),
    sa.Column('dogfriendly_place_work_hours', sa.String(length=50), nullable=False),
    sa.Column('dogfriendly_place_contacts', sa.String(length=50), nullable=False),
    sa.Column('dogfriendly_place_description', sa.Text(), nullable=False),
    sa.Column('dogfriendly_place_photo', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=50), nullable=False),
    sa.Column('user_date_of_birth', sa.Date(), nullable=False),
    sa.Column('user_email', sa.String(length=50), nullable=False),
    sa.Column('user_password_hash', sa.Text(), nullable=False),
    sa.Column('user_phone', sa.String(length=16), nullable=False),
    sa.Column('user_photo', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_info_user_email'), 'users_info', ['user_email'], unique=True)
    op.create_index(op.f('ix_users_info_user_phone'), 'users_info', ['user_phone'], unique=True)
    op.create_table('vet_clinics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vet_clinic_name', sa.String(length=50), nullable=False),
    sa.Column('vet_clinic_address', sa.String(length=50), nullable=False),
    sa.Column('vet_clinic_rating', sa.Numeric(), nullable=False),
    sa.Column('vet_clinic_work_hours', sa.String(length=50), nullable=False),
    sa.Column('vet_clinic_contacts', sa.String(length=50), nullable=False),
    sa.Column('vet_clinic_description', sa.Text(), nullable=False),
    sa.Column('vet_clinic_photo', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('llm_chats_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('message_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users_info.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_chats_messages_conversation_id'), 'llm_chats_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_llm_chats_messages_message_hash'), 'llm_chats_messages', ['message_hash'], unique=True)
    op.create_table('pets_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pet_name', sa.String(length=50), nullable=False),
    sa.Column('pet_date_of_birth', sa.Date(), nullable=False),
    sa.Column('pet_type', sa.Integer(), nullable=False),
    sa.Column('pet_breed', sa.Integer(), nullable=False),
    sa.Column('pet_pedigree', sa.Integer(), nullable=False),
    sa.Column('pet_neck_girth', sa.Numeric(), nullable=False),
    sa.Column('pet_breast_girth', sa.Numeric(), nullable=False),
    sa.Column('pet_length', sa.Numeric(), nullable=False),
    sa.Column('pet_is_sterylyzed', sa.Boolean(), nullable=True),
    sa.Column('pet_photo', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['pet_breed'], ['animals_breeds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pet_pedigree'], ['animals_pedigrees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pet_type'], ['animals_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users_info.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pet_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('custom_document_name', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['custom_document_name'], ['custom_documents_names.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pet_id'], ['pets_info.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shared_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shared_user_id', sa.Integer(), nullable=False),
    sa.Column('shared_pet_id', sa.Integer(), nullable=False),
    sa.Column('sharing_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sharing_end', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shared_pet_id'], ['pets_info.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shared_user_id'], ['users_info.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('smart_diets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('food_photo', sa.Text(), nullable=False),
    sa.Column('calculated_food_norm', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets_info.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suitable_dogfriendly_places',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets_info.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['place_id'], ['dog_friendly_places.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suitable_vet_clinics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['vet_clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pet_id'], ['pets_info.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suitable_vet_clinics')
    op.drop_table('suitable_dogfriendly_places')
    op.drop_table('smart_diets')
    op.drop_table('shared_users')
    op.drop_table('pet_documents')
    op.drop_table('pets_info')
    op.drop_index(op.f('ix_llm_chats_messages_message_hash'), table_name='llm_chats_messages')
    op.drop_index(op.f('ix_llm_chats_messages_conversation_id'), table_name='llm_chats_messages')
    op.drop_table('llm_chats_messages')
    op.drop_table('vet_clinics')
    op.drop_index(op.f('ix_users_info_user_phone'), table_name='users_info')
    op.drop_index(op.f('ix_users_info_user_email'), table_name='users_info')
    op.drop_table('users_info')
    op.drop_table('dog_friendly_places')
    op.drop_table('documents_types')
    op.drop_table('custom_documents_names')
    op.drop_table('animals_types')
    op.drop_table('animals_pedigrees')
    op.drop_table('animals_breeds')
    # ### end Alembic commands ###
