"""upgrade breeds

Revision ID: 59c8d8ad63ce
Revises: 7e2f4a1c9b3d
Create Date: 2026-05-14 12:17:37.384668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59c8d8ad63ce'
down_revision: Union[str, Sequence[str], None] = '7e2f4a1c9b3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('animals_breeds_animal_breed_name_key'), 'animals_breeds', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('animals_breeds_animal_breed_name_key'), 'animals_breeds', ['animal_breed'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
