"""add salons

Revision ID: 6c64d3aa923c
Revises: 93f77a4fbcd3
Create Date: 2026-05-10 23:45:22.786109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c64d3aa923c'
down_revision: Union[str, Sequence[str], None] = '5b0f8d4a7c21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grooming_salons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salon_name', sa.String(length=50), nullable=False),
    sa.Column('salon_city', sa.String(length=50), nullable=False),
    sa.Column('salon_street', sa.String(length=127), nullable=False),
    sa.Column('salon_building_number', sa.String(length=20), nullable=False),
    sa.Column('salon_lat', sa.Numeric(), nullable=False),
    sa.Column('salon_lon', sa.Numeric(), nullable=False),
    sa.Column('salon_geocoder_precision', sa.String(length=50), nullable=False),
    sa.Column('salon_working_hours', sa.String(length=255), nullable=False),
    sa.Column('salon_phone', sa.String(length=16), nullable=True),
    sa.Column('salon_website', sa.Text(), nullable=True),
    sa.Column('salon_status', sa.String(length=20), nullable=False),
    sa.Column('salon_last_verified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('salon_name', 'salon_city', 'salon_street', 'salon_building_number', name='unique_grooming_salon')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grooming_salons')
    # ### end Alembic commands ###
