"""fix to llm chats and messages

Revision ID: 921c0605b450
Revises: 3ae998d30070
Create Date: 2026-04-25 21:30:56.363178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '921c0605b450'
down_revision: Union[str, Sequence[str], None] = '3ae998d30070'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_chats_messages', sa.Column('parent_message_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_chats_messages', 'parent_message_id')
    # ### end Alembic commands ###
