"""update pets

Revision ID: 93f77a4fbcd3
Revises: 3de7b33dbfe2
Create Date: 2026-05-07 12:52:02.562284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93f77a4fbcd3'
down_revision: Union[str, Sequence[str], None] = '3de7b33dbfe2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets_info', sa.Column('pet_sex', sa.String(length=10), nullable=True))
    op.add_column('pets_info', sa.Column('pet_special_notes', sa.Text(), nullable=True))
    op.execute("UPDATE pets_info SET pet_sex = 'unknown' WHERE pet_sex IS NULL")

    op.alter_column("pets_info", "pet_sex", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pets_info', 'pet_special_notes')
    op.drop_column('pets_info', 'pet_sex')
    # ### end Alembic commands ###
