"""better table for auth

Revision ID: 9ded3226e584
Revises: 34c612ec2c36
Create Date: 2026-04-23 00:04:07.520996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ded3226e584'
down_revision: Union[str, Sequence[str], None] = '34c612ec2c36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auth_identities', 'user_password_hash',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('users_info', 'user_date_of_birth',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('users_info', 'user_phone_number',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    op.alter_column('users_info', 'user_email',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.execute(sa.text("DROP INDEX IF EXISTS ix_users_info_telegram_id"))
    op.drop_column('users_info', 'telegram_id')
    op.drop_column('users_info', 'user_password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_info', sa.Column('user_password_hash', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('users_info', sa.Column('telegram_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_users_info_telegram_id'), 'users_info', ['telegram_id'], unique=True)
    op.alter_column('users_info', 'user_email',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('users_info', 'user_phone_number',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
    op.alter_column('users_info', 'user_date_of_birth',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('auth_identities', 'user_password_hash',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
