"""add telegram fields to users_info

Revision ID: 9e11ca1f588d
Revises: 76c2a1766596
Create Date: 2026-03-12 12:12:55.028183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e11ca1f588d'
down_revision: Union[str, Sequence[str], None] = '76c2a1766596'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_info', sa.Column('telegram_id', sa.BIGINT(), nullable=True))
    op.add_column('users_info', sa.Column('auth_provider', sa.String(length=20), server_default=sa.text("'email'"), nullable=False))
    op.create_index(op.f('ix_users_info_telegram_id'), 'users_info', ['telegram_id'], unique=True)
    op.execute("UPDATE users_info SET auth_provider = 'email' WHERE auth_provider IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_info_telegram_id'), table_name='users_info')
    op.drop_column('users_info', 'auth_provider')
    op.drop_column('users_info', 'telegram_id')
    # ### end Alembic commands ###
