"""add llm-chat model

Revision ID: ca8a7eebe4c4
Revises: 001
Create Date: 2026-03-11 22:40:57.108279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca8a7eebe4c4'
down_revision: Union[str, Sequence[str], None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_chats_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('message_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users_info.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_chats_messages_conversation_id'), 'llm_chats_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_llm_chats_messages_message_hash'), 'llm_chats_messages', ['message_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_chats_messages_message_hash'), table_name='llm_chats_messages')
    op.drop_index(op.f('ix_llm_chats_messages_conversation_id'), table_name='llm_chats_messages')
    op.drop_table('llm_chats_messages')
    # ### end Alembic commands ###
