"""upgrade dogfriendly and add place types

Revision ID: da3d817a5e07
Revises: f36f6c2abeef
Create Date: 2026-05-11 23:54:35.234599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da3d817a5e07'
down_revision: Union[str, Sequence[str], None] = 'f36f6c2abeef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dog_friendly_place_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('place_name')
    )
    op.add_column('dog_friendly_places', sa.Column('dogfriendly_place_type_id', sa.Integer(), nullable=True))
    op.add_column('dog_friendly_places', sa.Column('dogfriendly_place_conditions', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'dog_friendly_places', 'dog_friendly_place_types', ['dogfriendly_place_type_id'], ['id'])
    op.alter_column('grooming_salons', 'salon_website',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('grooming_salons', 'salon_website',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'dog_friendly_places', type_='foreignkey')
    op.drop_column('dog_friendly_places', 'dogfriendly_place_conditions')
    op.drop_column('dog_friendly_places', 'dogfriendly_place_type_id')
    op.drop_table('dog_friendly_place_types')
    # ### end Alembic commands ###
