"""update vetclinics table

Revision ID: ec43268b0a8e
Revises: 7c3d9a2f1b6e
Create Date: 2026-03-23 23:28:14.038159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec43268b0a8e'
down_revision: Union[str, Sequence[str], None] = '7c3d9a2f1b6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_pet_id_created_by', 'pet_invite', ['pet_id', 'created_by'], unique=False)
    op.add_column('vet_clinics', sa.Column('vet_name', sa.String(length=50), nullable=False))
    op.add_column('vet_clinics', sa.Column('vet_city', sa.String(length=50), nullable=False))
    op.add_column('vet_clinics', sa.Column('vet_street', sa.String(length=127), nullable=False))
    op.add_column('vet_clinics', sa.Column('vet_building_number', sa.String(length=6), nullable=False))
    op.add_column('vet_clinics', sa.Column('vet_lat', sa.Numeric(), nullable=False))
    op.add_column('vet_clinics', sa.Column('vet_lon', sa.Numeric(), nullable=False))
    op.add_column('vet_clinics', sa.Column('vet_geocoder_precision', sa.String(length=50), nullable=False))
    op.add_column('vet_clinics', sa.Column('vet_working_hours', sa.String(length=255), nullable=False))
    op.add_column('vet_clinics', sa.Column('vet_is_24_7', sa.Boolean(), nullable=False))
    op.add_column('vet_clinics', sa.Column('vet_status', sa.String(length=20), nullable=False))
    op.add_column('vet_clinics', sa.Column('vet_phone', sa.String(length=16), nullable=True))
    op.add_column('vet_clinics', sa.Column('vet_website', sa.Text(), nullable=True))
    op.add_column('vet_clinics', sa.Column('vet_last_verified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('vet_clinics', 'vet_clinic_work_hours')
    op.drop_column('vet_clinics', 'vet_clinic_rating')
    op.drop_column('vet_clinics', 'vet_clinic_description')
    op.drop_column('vet_clinics', 'vet_clinic_name')
    op.drop_column('vet_clinics', 'vet_clinic_photo')
    op.drop_column('vet_clinics', 'vet_clinic_address')
    op.drop_column('vet_clinics', 'vet_clinic_contacts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vet_clinics', sa.Column('vet_clinic_contacts', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('vet_clinics', sa.Column('vet_clinic_address', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('vet_clinics', sa.Column('vet_clinic_photo', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('vet_clinics', sa.Column('vet_clinic_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('vet_clinics', sa.Column('vet_clinic_description', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('vet_clinics', sa.Column('vet_clinic_rating', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.add_column('vet_clinics', sa.Column('vet_clinic_work_hours', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('vet_clinics', 'vet_last_verified')
    op.drop_column('vet_clinics', 'vet_website')
    op.drop_column('vet_clinics', 'vet_phone')
    op.drop_column('vet_clinics', 'vet_status')
    op.drop_column('vet_clinics', 'vet_is_24_7')
    op.drop_column('vet_clinics', 'vet_working_hours')
    op.drop_column('vet_clinics', 'vet_geocoder_precision')
    op.drop_column('vet_clinics', 'vet_lon')
    op.drop_column('vet_clinics', 'vet_lat')
    op.drop_column('vet_clinics', 'vet_building_number')
    op.drop_column('vet_clinics', 'vet_street')
    op.drop_column('vet_clinics', 'vet_city')
    op.drop_column('vet_clinics', 'vet_name')
    op.drop_index('ix_pet_id_created_by', table_name='pet_invite')
    # ### end Alembic commands ###
