"""upgrade breeds 2

Revision ID: f0f5a33d143e
Revises: 59c8d8ad63ce
Create Date: 2026-05-14 12:30:52.800939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0f5a33d143e'
down_revision: Union[str, Sequence[str], None] = '59c8d8ad63ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_animal_breeds', 'animals_breeds', ['animal_breed', 'animal_type_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_animal_breeds', 'animals_breeds', type_='unique')
    # ### end Alembic commands ###
