"""drop custom document names support

Revision ID: f2a1b6c4d9e8
Revises: 7c3d9a2f1b6e
Create Date: 2026-03-23 18:10:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f2a1b6c4d9e8"
down_revision: Union[str, Sequence[str], None] = "7c3d9a2f1b6e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1
                FROM pg_constraint
                WHERE conname = 'pet_documents_custom_document_name_id_fkey'
            ) THEN
                ALTER TABLE pet_documents
                DROP CONSTRAINT pet_documents_custom_document_name_id_fkey;
            END IF;
        END
        $$;
        """
    )
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1
                FROM information_schema.columns
                WHERE table_name = 'pet_documents'
                  AND column_name = 'custom_document_name_id'
            ) THEN
                ALTER TABLE pet_documents DROP COLUMN custom_document_name_id;
            END IF;
        END
        $$;
        """
    )
    op.execute("DROP TABLE IF EXISTS custom_documents_names")


def downgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS custom_documents_names (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR(50) NOT NULL UNIQUE
        )
        """
    )
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1
                FROM information_schema.columns
                WHERE table_name = 'pet_documents'
                  AND column_name = 'custom_document_name_id'
            ) THEN
                ALTER TABLE pet_documents ADD COLUMN custom_document_name_id INTEGER NULL;
            END IF;
        END
        $$;
        """
    )
    op.create_foreign_key(
        "pet_documents_custom_document_name_id_fkey",
        "pet_documents",
        "custom_documents_names",
        ["custom_document_name_id"],
        ["id"],
        ondelete="SET NULL",
    )
