"""upgrade dogfriendly

Revision ID: f36f6c2abeef
Revises: 64b1204ff4e4
Create Date: 2026-05-11 00:09:01.989926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f36f6c2abeef'
down_revision: Union[str, Sequence[str], None] = '64b1204ff4e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dog_friendly_places', 'dogfriendly_place_is_24_7')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dog_friendly_places', sa.Column('dogfriendly_place_is_24_7', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
