"""fix vet clinics table

Revision ID: f9cd5961f532
Revises: ec43268b0a8e
Create Date: 2026-03-23 23:38:07.626987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9cd5961f532'
down_revision: Union[str, Sequence[str], None] = 'ec43268b0a8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vet_clinics', 'vet_building_number',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.String(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vet_clinics', 'vet_building_number',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False)
    # ### end Alembic commands ###
