PROFILE_BUTTON_TEXT = "Мой профиль"
ADD_PET_BUTTON_TEXT = "Регистрация питомца"
ACCEPT_INVITE_BUTTON_TEXT = "Принять доступ"
SHARE_PET_BUTTON_TEXT = "Поделиться питомцем"
REVOKE_ACCESS_BUTTON_TEXT = "Отозвать доступ"
UPDATE_PET_PHOTO_BUTTON_TEXT = "Обновить фото"
DELETE_PET_PHOTO_BUTTON_TEXT = "Удалить фото"
BACK_TO_PROFILE_BUTTON_TEXT = "Вернуться в профиль"
NO_BREED_BUTTON_TEXT = "без породы"

YES_TEXT = "Да"
NO_TEXT = "Нет"

BOT_RECONNECT_DELAY_SECONDS = 5

RESERVED_MESSAGE_TEXTS = {
    PROFILE_BUTTON_TEXT,
    ADD_PET_BUTTON_TEXT,
    ACCEPT_INVITE_BUTTON_TEXT,
    SHARE_PET_BUTTON_TEXT,
    REVOKE_ACCESS_BUTTON_TEXT,
    UPDATE_PET_PHOTO_BUTTON_TEXT,
    DELETE_PET_PHOTO_BUTTON_TEXT,
    BACK_TO_PROFILE_BUTTON_TEXT,
    YES_TEXT,
    NO_TEXT,
    NO_BREED_BUTTON_TEXT,
}
