PROFILE_BUTTON_TEXT = "Мой профиль"
ADD_PET_BUTTON_TEXT = "Регистрация питомца"
ACCEPT_INVITE_BUTTON_TEXT = "Принять доступ"
LLM_CHAT_BUTTON_TEXT = "Чат с ИИ"
NEW_LLM_CHAT_BUTTON_TEXT = "Новый чат"
SHARE_PET_BUTTON_TEXT = "Поделиться питомцем"
REVOKE_ACCESS_BUTTON_TEXT = "Отозвать доступ"
UPDATE_PET_PHOTO_BUTTON_TEXT = "Обновить фото"
DELETE_PET_PHOTO_BUTTON_TEXT = "Удалить фото"
DELETE_PET_BUTTON_TEXT = "Удалить питомца"
SHOW_PET_DOCUMENTS_BUTTON_TEXT = "Документы питомца"
ADD_PET_DOCUMENT_BUTTON_TEXT = "Добавить документ"
DELETE_PET_DOCUMENT_BUTTON_TEXT = "Удалить документ"
BACK_TO_PROFILE_BUTTON_TEXT = "Вернуться в профиль"
NO_BREED_BUTTON_TEXT = "без породы"

YES_TEXT = "Да"
NO_TEXT = "Нет"

BOT_RECONNECT_DELAY_SECONDS = 5

BUTTON_TEXTS = (
    PROFILE_BUTTON_TEXT,
    ADD_PET_BUTTON_TEXT,
    ACCEPT_INVITE_BUTTON_TEXT,
    LLM_CHAT_BUTTON_TEXT,
    NEW_LLM_CHAT_BUTTON_TEXT,
    SHARE_PET_BUTTON_TEXT,
    REVOKE_ACCESS_BUTTON_TEXT,
    UPDATE_PET_PHOTO_BUTTON_TEXT,
    DELETE_PET_PHOTO_BUTTON_TEXT,
    DELETE_PET_BUTTON_TEXT,
    SHOW_PET_DOCUMENTS_BUTTON_TEXT,
    ADD_PET_DOCUMENT_BUTTON_TEXT,
    DELETE_PET_DOCUMENT_BUTTON_TEXT,
    BACK_TO_PROFILE_BUTTON_TEXT,
)

RESERVED_MESSAGE_TEXTS = {
    *BUTTON_TEXTS,
    YES_TEXT,
    NO_TEXT,
    NO_BREED_BUTTON_TEXT,
}
